name: "TomoStash"
tagline: "Pineapple-Certfied Online Digital Tomes Library"
description: "Pineapple-Certfied Online Digital Tomes Library"
#keywords: "Pineapple, Pineapple Pizza, Pineapple House"
#email: "pineapple@example.com"
#linkedin: "https://www.linkedin.com/"
#twitter: "https://twitter.com/"
github: "https://github.com/GamingShitposting/TomoStash"

baseurl: "/TomoStash"
highlighter: rouge
layout: project
sass:
  sass_dir: assets/scss
  style: compressed

collections:
  tomes:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: tomes
    values:
      layout: tome

extra:
  store: "https://gamingshitposting.github.io/docs-bin-1"
